import React from 'react'
import OffersDetails from '../Components/OffersDetails.tsx'
export default function RecommendationsOffers() {
  return (
    <div className='container mx-auto p-4 lg:p-8'>
        <p className='font-bold text-3xl lg:text-4xl text-left text-[#1D267D]'> Here's what you can look forward to:</p>
        <OffersDetails srcImg={"/Assets/k1.jpg"} title="K2 (Mount Godwin Austen)" details="As the snow blankets the towering peaks of the Karakoram Range, I am thrilled to extend to you an exclusive invitation to embark on the ultimate ski adventure at K2, also known as Mount Godwin Austen. Imagine yourself surrounded by the breathtaking beauty of the world's second-highest mountain, carving through pristine powder and conquering the heights in one of the most exhilarating skiing experiences on the planet." date="18/2/2025-27/2/2025" price="2 Persons: max price 1000$"/>
        <OffersDetails srcImg={"/Assets/Moraine2.jpg"} title="Moraine Lake" details="As summer approaches, I am delighted to extend to you an exclusive invitation to experience the unparalleled beauty of Moraine Lake in the heart of the Canadian Rockies. Imagine yourself surrounded by towering snow-capped peaks, shimmering turquoise waters, and lush alpine meadows—a wilderness sanctuary waiting to be explored." date="12/7/2024-19/7/2024" price="2 Persons: max price 1500$"/>
        <OffersDetails srcImg={"/Assets/Denali3.jpg"} title="Mount Denali" details="As the festive season draws near, I am delighted to extend to you an exclusive invitation to experience the magic of Christmas amidst the awe-inspiring beauty of Mount Denali. Nestled in the heart of Alaska's wilderness, Mount Denali promises a holiday retreat like no other, where snow-capped peaks, pristine forests, and the spirit of the season converge to create unforgettable memories." date="23/12/2024-28/12/2024" price="2 Persons: max price 2000$"/>
        <OffersDetails srcImg={"/Assets/Caraibe1.jpg"} title="Caribbean Islands" details="With Easter just around the corner, I'm thrilled to extend to you an invitation for an extraordinary holiday experience in the stunning Caribbean Isles. Imagine waking up to the gentle sound of waves lapping against the shore, surrounded by palm-fringed beaches and azure waters that stretch as far as the eye can see. Our team has curated an exclusive Easter escape that promises relaxation, adventure, and unparalleled luxury in one of the most beautiful destinations on earth." date="2/05/2024-9/05/2024" price="2 Persons: max price 2000$"/>
        <OffersDetails srcImg={"/Assets/Kili3.jpg"} title="Mount Kilimanjaro" details="As we stand on the brink of a new year, I am thrilled to extend to you an extraordinary opportunity to welcome the dawn of 20XX at the majestic Mount Kilimanjaro. Imagine standing atop the highest peak in Africa, surrounded by the breathtaking beauty of the Tanzanian landscape, as you embark on a journey of adventure and self-discovery in one of the world's most iconic destinations." date="29/12/2024-4/1/2025" price="2 Persons: max price 1500$"/>
        <OffersDetails srcImg={"/Assets/Matt3.webp"} title="Mount Matterhorn" details="As the summer sun graces the Swiss Alps with its warmth, I am thrilled to extend to you an exclusive invitation to experience the majestic beauty of Mount Matterhorn. Imagine yourself surrounded by towering peaks, verdant meadows, and the crisp alpine air—a haven of tranquility waiting to be explored." date="5/5/2024-10/6/2024" price="2 Persons: max price 1000$"/>
    </div>
  )
}
